### ISSUE TITLE
Recommendation Engine code

### ISSUE THREAD

**Issue by skkeyan-mlai** [skkeyan-mlai/navigate-data-science#6]
Category 4 in Navigating the data science world is on "Unsupervised ML using Structured data". I have already added the code for Clustering but would like to have the code added for Recommender system. Any help is welcome.

**Comment by skkeyan** [comment]
I would like to help. Do you have a specific implementation in mind?

**Comment by skkeyan-mlai** [comment]
Thanks. My preference is to have the example done for the movie lens dataset.
